on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  Creating-PR-using-AIPR:
    if: ${{ (github.event_name == 'issues' && 
             contains( github.event.label.name, 'AIPR')) || 
            (github.event_name == 'issue_comment' && 
             github.event.issue.pull_request &&
             contains( github.event.comment.body, 'Create PR with AIPR ðŸš€')) }}
    runs-on: ubuntu-latest
    steps:
    - name: Executing AIPR action
      uses: alexanmtz/AIPR@main
      with:
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        openai_tokens: 1400
        file_chunks: 0
        target_branch: master
        
